### ISSUE TITLE
Error running `ember new my-app -b @glimmer/blueprint`

### ISSUE THREAD

**Issue by d3chapma** [glimmerjs/glimmer.js#12]
Edit: Perhaps this is an issue for the `ember-cli` repo?

Below is the output to my terminal. Am I doing something wrong? 

```
[dc] ~/Projects/web  % ember -v
ember-cli: 2.15.1
node: 6.9.1
os: darwin x64
```

```
[dc] ~/Projects/web  % ember new my-app -b @glimmer/blueprint
installing blueprint
  create .editorconfig
  create .watchmanconfig
  create README.md
  create config/environment.js
  create config/module-map.d.ts
  create config/resolver-configuration.d.ts
  create config/targets.js
  create ember-cli-build.js
  create .gitignore
  create package.json
  create public/robots.txt
  create src/index.ts
  create src/main.ts
  create src/ui/components/my-app/component-test.ts
  create src/ui/components/my-app/component.ts
  create src/ui/components/my-app/template.hbs
  create src/ui/index.html
  create src/ui/styles/app.scss
  create src/utils/test-helpers/test-helper.ts
  create testem.json
  create tsconfig.json
  create yarn.lock
Error creating new application. Removing generated directory `./my-app`
Command failed: yarn install --ignore-optional --non-interactive
warning "ember-build-utilities@0.4.0" has incorrect peer dependency "@glimmer/compiler@> 0.26.0".
warning "@glimmer/inline-precompile@1.0.1" has incorrect peer dependency "@glimmer/compiler@> 0.23.0 || > 0.24.0-alpha.1 || > 0.25.0-alpha.1".
warning "babel-plugin-glimmer-inline-precompile@1.2.0" has incorrect peer dependency "@glimmer/compiler@> 0.23.0 || > 0.24.0-alpha.1 || > 0.25.0-alpha.1".
warning "@glimmer/test-helpers@0.30.0" has incorrect peer dependency "@glimmer/component@>= 0.4.0".
error /Users/dc/Projects/web/my-app/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments:
Directory: /Users/dc/Projects/web/my-app/node_modules/node-sass
Output:
module.js:471
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/dc/Projects/web/my-app/node_modules/readable-stream/lib/_stream_readable.js:26:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

yarn install v1.0.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by josemarluedke** [comment]
I believe this issue is the same as described here: https://github.com/glimmerjs/glimmer-blueprint/issues/63

**Comment by d3chapma** [comment]
That fixed it for me. Thanks!
