### ISSUE TITLE
Error running `ember new my-app -b @glimmer/blueprint`, using ember-cli 3.5.1 & windows

### ISSUE THREAD

**Issue by lifeart** [glimmerjs/glimmer.js#158]
![image](https://user-images.githubusercontent.com/1360552/48893052-760a9700-ee50-11e8-8853-d8f40e4bc0f9.png)

```
ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Cannot find module 'C:\Users\ALEKSA~1\AppData\Local\Temp\ember-cli1181022-17076-133qt6r.fnni\node_modules\@glimmer\blueprint\package.json'
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Cannot find module 'C:\Users\ALEKSA~1\AppData\Local\Temp\ember-cli1181022-17076-133qt6r.fnni\node_modules\@glimmer\blueprint\package.json'
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: Cannot find module 'C:\Users\ALEKSA~1\AppData\Local\Temp\ember-cli1181022-17076-133qt6r.fnni\node_modules\@glimmer\blueprint\package.json'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at InstallBlueprintTask._validateNpmModule (C:\Users\Aleksandr_Kanunnikov\AppData\Roaming\npm\node_modules\ember-cli\lib\tasks\install-blueprint.js:133:15)
    at _createTempFolder.then.then.modulePath (C:\Users\Aleksandr_Kanunnikov\AppData\Roaming\npm\node_modules\ember-cli\lib\tasks\install-blueprint.js:92:14)
    at tryCatcher (C:\Users\Aleksandr_Kanunnikov\AppData\Roaming\npm\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:323:19)
    at invokeCallback (C:\Users\Aleksandr_Kanunnikov\AppData\Roaming\npm\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:495:31)
    at publish (C:\Users\Aleksandr_Kanunnikov\AppData\Roaming\npm\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:481:7)
    at flush (C:\Users\Aleksandr_Kanunnikov\AppData\Roaming\npm\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:2402:5)
```

same for: 
* `ember-cli@3.6.0-beta.1`
* `ember-cli@3.4.3`
* `ember-cli@3.3.0`
* `ember-cli@3.1.3`

**Comment by bakerac4** [comment]
Im seeing the same thing on MAC -> ember-cli@3.8.0. Any ideas or workarounds?

**Comment by rwjblue** [comment]
Anyone know if this is _only_ failing on windows or if all platforms fail?

**Comment by bakerac4** [comment]
Its failing on mac for me and & windows for @lifeart.

**Comment by rwjblue** [comment]
@lifeart - Can you confirm if that addresses?

**Comment by lifeart** [comment]
one more attempt:

`ember new my-app -b @glimmer/blueprint` 

```
Error creating new application. Removing generated directory `./my-app`
Cannot find module 'C:\Users\ALEKSA~1\AppData\Local\Temp\ember-cli11926-800-1yms5li.hx3e\node_modules\@glimmer\blueprint\package.json'

Stack Trace and Error Report: C:\Users\ALEKSA~1\AppData\Local\Temp/error.dump.b1188e466fa123d8d4bb66f7daaef987.log

```

after 

`npm cache clear --force`

```
Error creating new application. Removing generated directory `./my-app`
Cannot find module 'C:\Users\ALEKSA~1\AppData\Local\Temp\ember-cli11926-20220-144utn4.rqin\node_modules\@glimmer\blueprint\package.json'


Stack Trace and Error Report: C:\Users\ALEKSA~1\AppData\Local\Temp/error.dump.cd4ec9b9b1bd46aac669cab8e5237fc8.log

```


looks like npm cache cleanup not working(

**Comment by ASH-Anthony** [comment]
I'm not sure if it will fix this specific issue, but using the suggestion from https://github.com/ember-cli/ember-octane-blueprint/issues/88 to install the blueprint locally worked to fix the same issue with an octane blueprint

**Comment by lifeart** [comment]
```
$ npx ember-cli new glimmer -b @glimmer/blueprtint
npx: installed 783 in 30.38s

Error creating new application. Removing generated directory `./glimmer`
Command failed: npm install @glimmer/blueprtint
npm ERR! code E404
npm ERR! 404 Not Found: @glimmer/blueprtint@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lifeart\AppData\Roaming\npm-cache\_logs\2019-04-27T07_38_31_410Z-debug.log




Stack Trace and Error Report: C:\Users\lifeart\AppData\Local\Temp/error.dump.8ff47cf0e6307ffcac0f0b7791671220.log

```
