### ISSUE TITLE
Windows build error / New glimmer app (0.14 blueprint)

### ISSUE THREAD

**Issue by lifeart** [glimmerjs/glimmer.js#187]
```
C:/Users/lifeart/Documents/repos/glimmer-app/tmp/rollup_with_dependencies-cache_path-qi0xep0r.tmp/build/tests.js: Bad character escape sequence (3:15)
  1 | import './src\index.lint-test';
  2 | import './src\main.lint-test';
> 3 | import './src\ui\components\Glimmer\component-test';
    |                ^
  4 | import './src\ui\components\Glimmer\component-test.lint-test';
  5 | import './src\ui\components\Glimmer\component.lint-test';
  6 | import './src\ui\components\Table\component.lint-test';

```

**Comment by lifeart** [comment]
```
ERROR Summary:

  - broccoliBuilderErrorStack: SyntaxError: C:/Users/lifeart/Documents/repos/glimmer-app/tmp/rollup_with_dependencies-cache_path-qi0xep0r.tmp/build/tests.js: Bad character escape sequence (3:15)
    at error (C:\Users\lifeart\Documents\repos\glimmer-app\node_modules\rollup\dist\rollup.js:224:15)
    at Object.error (C:\Users\lifeart\Documents\repos\glimmer-app\node_modules\rollup\dist\rollup.js:17174:21)
    at C:\Users\lifeart\Documents\repos\glimmer-app\node_modules\rollup\dist\rollup.js:17183:29
  - code: [undefined]
  - codeFrame: [0m [90m 1 | [39m[36mimport[39m [32m'./src\index.lint-test'[39m[33m;[39m
 [90m 2 | [39m[36mimport[39m [32m'./src\main.lint-test'[39m[33m;[39m
[31m[1m>[22m[39m[90m 3 | [39m[36mimport[39m [32m'./src\ui\components\Glimmer\component-test'[39m[33m;[39m
 [90m   | [39m               [31m[1m^[22m[39m
 [90m 4 | [39m[36mimport[39m [32m'./src\ui\components\Glimmer\component-test.lint-test'[39m[33m;[39m
 [90m 5 | [39m[36mimport[39m [32m'./src\ui\components\Glimmer\component.lint-test'[39m[33m;[39m
 [90m 6 | [39m[36mimport[39m [32m'./src\ui\components\Table\component.lint-test'[39m[33m;[39m[0m
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `RollupWithDependencies` plugin. 💥
C:/Users/lifeart/Documents/repos/glimmer-app/tmp/rollup_with_dependencies-cache_path-qi0xep0r.tmp/build/tests.js: Bad character escape sequence (3:15)
  - errorType: Build Error
  - location:
    - column: 15
    - line: 3
  - message: Build Canceled: Broccoli Builder ran into an error with `RollupWithDependencies` plugin. 💥
C:/Users/lifeart/Documents/repos/glimmer-app/tmp/rollup_with_dependencies-cache_path-qi0xep0r.tmp/build/tests.js: Bad character escape sequence (3:15)
  - name: Error
  - nodeAnnotation: RollupWithDependencies
  - nodeName: RollupWithDependencies
  - originalErrorMessage: C:/Users/lifeart/Documents/repos/glimmer-app/tmp/rollup_with_dependencies-cache_path-qi0xep0r.tmp/build/tests.js: Bad character escape sequence (3:15)
  - stack: SyntaxError: C:/Users/lifeart/Documents/repos/glimmer-app/tmp/rollup_with_dependencies-cache_path-qi0xep0r.tmp/build/tests.js: Bad character escape sequence (3:15)
    at error (C:\Users\lifeart\Documents\repos\glimmer-app\node_modules\rollup\dist\rollup.js:224:15)
    at Object.error (C:\Users\lifeart\Documents\repos\glimmer-app\node_modules\rollup\dist\rollup.js:17174:21)
    at C:\Users\lifeart\Documents\repos\glimmer-app\node_modules\rollup\dist\rollup.js:17183:29
```

**Comment by lifeart** [comment]
looks like issue fixed in https://github.com/glimmerjs/glimmer-application-pipeline/commit/d564322418775174d71238061bd69caff1866cfa#diff-b705c22401009908bcb9fe8d48c481b4

**Comment by lifeart** [comment]
but, build with fix has braking change in ts version

**Comment by lifeart** [comment]
gonna close it because i'm stupid and has typo in blueprint name
