### ISSUE TITLE
"Cannot find module" in temp directory when '... new myapp -b @glimmer/blueprint' on Win10

### ISSUE THREAD

**Issue by stonecooler** [glimmerjs/glimmer.js#277]
Hi,

after I seen glimmer.js in action on jsconfeu last weekend I started to work through the guides from "glimmerjs.com". Installing on Win10 works fine:

```
> ember -v 
ember-cli: 2.14.0-beta.1
node: 6.10.3
os: win32 x64
```
But I got an error when creating a new app with `ember new my-app -b @glimmer/blueprint`:
```
Error creating new application. Removing generated directory `./my-app`
Cannot find module 'C:\Users\stste\AppData\Local\Temp\ember-cli11749-12384-ak8wi2.6h5llyp66r\node_modules\@glimmer\blueprint\package.json'
Error: Cannot find module 'C:\Users\stste\AppData\Local\Temp\ember-cli11749-12384-ak8wi2.6h5llyp66r\node_modules\@glimmer\blueprint\package.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at InstallBlueprintTask._validateNpmModule (C:\Users\stste\AppData\Local\Yarn\config\global\node_modules\ember-cli\lib\tasks\install-blueprint.js:128:15)
    at _createTempFolder.then.then.modulePath (C:\Users\stste\AppData\Local\Yarn\config\global\node_modules\ember-cli\lib\tasks\install-blueprint.js:91:14)
    at tryCatch (C:\Users\stste\AppData\Local\Yarn\config\global\node_modules\rsvp\dist\rsvp.js:539:12)
    at invokeCallback (C:\Users\stste\AppData\Local\Yarn\config\global\node_modules\rsvp\dist\rsvp.js:554:13)
    at publish (C:\Users\stste\AppData\Local\Yarn\config\global\node_modules\rsvp\dist\rsvp.js:522:7)
    at flush (C:\Users\stste\AppData\Local\Yarn\config\global\node_modules\rsvp\dist\rsvp.js:2414:5)
```
It seems that the generating of a temp directory during the blueprint install does not work - I guess on Win10 only? The `ember-cli...` directory is really not in  `...AppData\Local\Temp\` in the file system.

Can someone help? Thanks.

**Comment by locks** [comment]
Closing as I believe this is no longer relevant. If you encounter this problem let us know!
