### ISSUE TITLE
Internal glimmer error when missing component invoked with curlies

### ISSUE THREAD

**Issue by BryanCrotaz** [glimmerjs/glimmer.js#314]
```
Cannot read property 'getCapabilities' of undefined@ 40 ms
Source:     
TypeError: Cannot read property 'getCapabilities' of undefined
    at Object.evaluate (http://192.168.0.10:7357/assets/vendor.js:50753:52)
    at AppendOpcodes.evaluate (http://192.168.0.10:7357/assets/vendor.js:49084:19)
    at LowLevelVM.evaluateSyscall (http://192.168.0.10:7357/assets/vendor.js:52502:22)
    at LowLevelVM.evaluateInner (http://192.168.0.10:7357/assets/vendor.js:52458:14)
    at LowLevelVM.evaluateOuter (http://192.168.0.10:7357/assets/vendor.js:52450:14)
    at JitVM.next (http://192.168.0.10:7357/assets/vendor.js:53505:24)
    at JitVM.execute (http://192.168.0.10:7357/assets/vendor.js:53477:25)
    at TryOpcode.handleException (http://192.168.0.10:7357/assets/vendor.js:52623:23)
    at UpdatingVMFrame.handleException (http://192.168.0.10:7357/assets/vendor.js:52857:31)
    at UpdatingVM.throw (http://192.168.0.10:7357/assets/vendor.js:52554:18)
```
it happens when you refer to a curly-component that doesn't exist in a test template - changing it to angle brackets gives a more useful message `Cannot find component my-missing-component`. Only happens when you're passing attributes.
```
await render (hbs`{{my-missing-component}}`); // gives a useful missing component error
await render (hbs`{{my-missing-component select=false}}`); // gives the cryptic glimmer error
await render (hbs`<MyMissingComponent @select={{false}}/>`); // gives a useful missing component error
```

**Comment by boris-petrov** [comment]
The same is true for missing helpers, by the way: `{{#if (my-missing-helper)}}{{/if}}` leads to the exact same error.
